#!/bin/bash
set -euo pipefail

# LLaDA2 + HG+TILG best known GSM8K setting (no-KL gate)
cd /home/tzluo/TILg_final

MASTER_PORT=${MASTER_PORT:-23671} \
CUDA_VISIBLE_DEVICES=${CUDA_VISIBLE_DEVICES:-4} \
MODEL_PATH=${MODEL_PATH:-/data/ckpt/LLaDa2.0-mini} \
TASKS=gsm8k_llada_mini \
MODE=tilg \
GEN_LENGTH=1024 \
BLOCK_LENGTH=32 \
THRESHOLD=0.95 \
KL_THRESHOLD=999 \
KL_HISTORY_LENGTH=1 \
TILG_EXTRA_KL_THRESHOLD=999 \
HG_HISTORY_LEN=2 \
HG_MIN_STREAK=4 \
HISTORY_GATE_CONFIDENCE_ESCAPE=0.97 \
TILG_EXTRA_CONF_FLOOR=0.85 \
TILG_EXTRA_MAX=1 \
TILG_CFG_LIKE_ENABLED=True \
TILG_GUIDANCE_WEIGHT=0.3 \
TILG_EMA_DECAY=0.95 \
TILG_RERANK_LAMBDA=0.03 \
bash scripts/run_llada2_dinfer_tilg.sh
